export enum UserRole {
  STP_ADMIN = 'STP_ADMIN',
  DIRECTOR = 'DIRECTOR',
  TRAINER = 'TRAINER',
  SUB_TRAINER = 'SUB_TRAINER',
  SECRETARIA = 'SECRETARIA',
  ATHLETE = 'ATHLETE',
}

export enum EmailStatus {
  ERROR = 'ERROR',
  SUCCESS = 'SUCCESS',
}